platform :ios, ‘8.0’

target 'My_News_Swift' do
use_frameworks!
    pod 'MJExtension', '2.5.16'
    pod 'MBProgressHUD', '~> 0.9.1'
    pod 'pop', '~> 1.0'
    pod 'POP+SnapKit', '~> 3.0.2'
    pod 'libextobjc', '~> 0.4'
    pod 'SVProgressHUD'
    pod 'Kingfisher', '~>3.3.4'
    pod 'Alamofire', '~> 4.3.0'
    pod 'SwiftyJSON', '~> 3.1.4'
    pod 'MJRefresh'
#    pod 'CryptoSwift'
    pod 'ESPullToRefresh'
    pod 'GTMRefresh'
    pod 'RealmSwift', '~> 3.0.0-beta.2'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.2'
        end
    end
end
